version: '3'
services:
  app:
    container_name: app_api_2
    restart: always
    build: .
    environment:
      - MONGO_INITDB_DATABASE=api2
      - MONGO_URL=mongodb://admin:46UeIA53nSKeeeryixbu@mongo:27018/api2?authSource=admin&readPreference=primary&directConnection=true&ssl=false
    ports:
      - '9002:9002'
    external_links:
      - mongo
  mongo:
    container_name: mongo_2
    image: mongo
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=46UeIA53nSKeeeryixbu
      - MONGO_INITDB_DATABASE=api2
    ports:
      - '27018:27018'